# Generated by Django 6.0.2 on 2026-02-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_consumed"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumed",
            name="poster_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
