# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="media_type",
            field=models.CharField(
                choices=[("media", "Movies & TV"), ("person", "Person")],
                default="media",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Consumed",
        ),
    ]
